version: "3"
services:
  load_candles:
    build: ./src
    environment:
      - PG_HOST
      - PG_DATABASE
      - PG_USER
      - PG_PASSWORD
      - LOOKBACK=200
    command:
      - python
      - /app/load_candles.py
