version: "3"
services:
  load_candles:
    build: ./src
    environment:
      - PG_HOST
      - PG_DATABASE
      - PG_USER
      - PG_PASSWORD
      - DAYS_TO_LOAD=1
    command:
      - python
      - /app/load_candles.py
  ci_strategy:
    build: ./src
    environment:
      - PG_HOST
      - PG_DATABASE
      - PG_USER
      - PG_PASSWORD
      - LOOKBACK_DAYS=1
    command:
      - python
      - /app/ci_strategy.py
